### ISSUE TITLE
Failing integration tests.

### ISSUE THREAD

**Issue by marcodlk** [dreedyman/mstc-web-astros#2] opened 2022-01-13 16:42 UTC
## Expected Behavior
Run `make test` and pass integration tests.

## Current Behavior
Unit tests pass but integration tests fail with connection error:
```
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
See the full output of `make test` [here](https://github.com/dreedyman/mstc-web-astros/files/7863943/test_output.txt).

## Steps to Reproduce
1. Pull latest main branch.
2. Run `make cleanall`
3. Run `make test`

### OS

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1519
```

### Kubernetes

```
$ kubectl version  
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

### Python

```
$ python --version
Python 3.9.7
```

### Kubernetes Deployment

```
$ make deploy
$ make list
NAME                              READY   STATUS    RESTARTS   AGE
pod/mstc-astros-6dfc89bb6-zcdd5   1/1     Running   0          18s

NAME                      TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)                         AGE
service/mstc-astros-svc   NodePort   10.98.95.246   <none>        8080:31001/TCP,8081:31002/TCP   18s

NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/mstc-astros   1/1     1            1           18s

NAME                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/mstc-astros-6dfc89bb6   1         1         1       18s

NAME       	NAMESPACE	REVISION	UPDATED                             	STATUS CHART       	APP VERSION
mstc-astros	mstc-dev 	1       	2022-01-13 10:44:52.753289 -0500 EST	deployeastros-0.1.0	0.2.0      
```

Pod description:
```
$ kubectl describe pod mstc-astros-6dfc89bb6-zcdd5 -n mstc-dev
Name:         mstc-astros-6dfc89bb6-zcdd5
Namespace:    mstc-dev
Priority:     0
Node:         docker-desktop/192.168.65.4
Start Time:   Thu, 13 Jan 2022 10:44:53 -0500
Labels:       app=mstc-astros
              pod-template-hash=6dfc89bb6
Annotations:  <none>
Status:       Running
IP:           10.1.0.78
IPs:
  IP:           10.1.0.78
Controlled By:  ReplicaSet/mstc-astros-6dfc89bb6
Containers:
  mstc-astros-container:
    Container ID:   docker://0c3082c8198e0ba863b9d550d721bede3770002f5dd3ead07d5b8b80a0a53abb
    Image:          mstc-astros:0.2.0
    Image ID:       docker://sha256:112240e934439f33e4e7e620de303c12bbb5125e281031907fc35ba7cf6fc428
    Ports:          8080/TCP, 8081/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Thu, 13 Jan 2022 10:44:58 -0500
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-mrwcp (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  kube-api-access-mrwcp:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  19m   default-scheduler  Successfully assigned mstc-dev/mstc-astros-6dfc89bb6-zcdd5 to docker-desktop
  Normal  Pulled     19m   kubelet            Container image "mstc-astros:0.2.0" already present on machine
  Normal  Created    19m   kubelet            Created container mstc-astros-container
  Normal  Started    19m   kubelet            Started container mstc-astros-container
```

Service description:
```
$ kubectl describe svc mstc-astros-svc -n mstc-dev 
Name:                     mstc-astros-svc
Namespace:                mstc-dev
Labels:                   app.kubernetes.io/managed-by=Helm
Annotations:              meta.helm.sh/release-name: mstc-astros
                          meta.helm.sh/release-namespace: mstc-dev
Selector:                 app=mstc-astros
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.98.95.246
IPs:                      10.98.95.246
Port:                     mstc-astros-rest  8080/TCP
TargetPort:               8080/TCP
NodePort:                 mstc-astros-rest  31001/TCP
Endpoints:                10.1.0.78:8080
Port:                     mstc-astros-data  8081/TCP
TargetPort:               8081/TCP
NodePort:                 mstc-astros-data  31002/TCP
Endpoints:                10.1.0.78:8081
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

Deployment description:
```
$ kubectl describe deployment mstc-astros -n mstc-dev
Name:                   mstc-astros
Namespace:              mstc-dev
CreationTimestamp:      Thu, 13 Jan 2022 10:44:53 -0500
Labels:                 app=mstc-astros
                        app.kubernetes.io/managed-by=Helm
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: mstc-astros
                        meta.helm.sh/release-namespace: mstc-dev
Selector:               app=mstc-astros
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=mstc-astros
  Containers:
   mstc-astros-container:
    Image:        mstc-astros:0.2.0
    Ports:        8080/TCP, 8081/TCP
    Host Ports:   0/TCP, 0/TCP
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   mstc-astros-6dfc89bb6 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  24m   deployment-controller  Scaled up replica set mstc-astros-6dfc89bb6 to 1
```
I can confirm that the astros app is working from within the cluster, both via pod IP and service IP.
```
$ kubectl run -it --rm --restart=Never busybox --image=gcr.io/google-containers/busybox sh
If you don't see a command prompt, try pressing enter.

/ # wget -qO- 10.1.0.78:8080
hello, 10.1.0.78:8080/ # 
/ # wget -qO- 10.1.0.78:8081
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Directory listing for /</title>
</head>
<body>
<h1>Directory listing for /</h1>
<hr>
<ul>
</ul>
<hr>
</body>
</html>
/ # wget -qO- 10.98.95.246:8080
hello, 10.98.95.246:8080/ # 
/ #  
```

**Comment by dreedyman** [comment] 2022-01-13 17:00
I cannot reproduce this. Run kubectl logs mstc-astros-pod -n mstic-dev.

Note that mstc-astros-pod will be something like mstc-astros-6dfc89bb6-zcdd5

**Comment by marcodlk** [comment] 2022-01-13 17:11
```
$ kubectl logs -f mstc-astros-6dfc89bb6-zcdd5 -n mstc-dev
[2022-01-13 15:45:00 +0000] [9] [INFO] Starting gunicorn 20.1.0
[2022-01-13 15:45:00 +0000] [9] [INFO] Listening at: http://0.0.0.0:8080 (9)
[2022-01-13 15:45:00 +0000] [9] [INFO] Using worker: sync
[2022-01-13 15:45:00 +0000] [10] [INFO] Booting worker with pid: 10
2022-01-13 15:45:01,327 Created dir: /app/astros/scratch
2022-01-13 16:14:12,272 hello
10.1.0.79 - - [13/Jan/2022 16:14:20] "GET / HTTP/1.1" 200 -
2022-01-13 16:34:52,591 hello
^C
```
Note that I was able to successfully reach the server via pod IP and service IP, as shown in the logs. The issue seems to be that I am unable to reach the service from outside the cluster.

I don't appear to have kube-proxy running... is that a red flag?
```
$  ps auxw | grep kube-proxy
delannmt         19967   0.0  0.0  4277504    700 s012  S+   12:04PM   0:00.00 grep kube-proxy
```

**Comment by dreedyman** [comment] 2022-01-13 17:14
This is to be expected as:

1. There is not ingress controller deployed (working on that)
2. And there is no kube proxy running

Closing as this is a work in progress

**Closed by dreedyman** 2022-01-13 17:14 UTC

**Comment by marcodlk** [comment] 2022-01-13 17:22
FWIW, I do have kube-proxy running. It's on the Docker Desktop node.

$ kubectl get pods -o wide --all-namespaces | grep kube-proxy
kube-system   kube-proxy-6f4m4                         1/1     Running   0          48d   192.168.65.4   docker-desktop   <none>           <none>

**Comment by marcodlk** [comment] 2022-01-13 17:48
So this is interesting... I explicitly setup the port forwarding on from the service to the host and was able to at least reach the service with curl.

Window 1:
```
$ kubectl port-forward service/mstc-astros-svc 31001:8080 -n mstc-dev
Forwarding from 127.0.0.1:31001 -> 8080
Forwarding from [::1]:31001 -> 8080
Handling connection for 31001
```
Window2:
```
$ curl -X GET http://localhost:31001
hello, localhost:31001$       
```

Still no luck with the tests though... same connection error.

**Comment by dreedyman** [comment] 2022-01-13 17:51
The way the pod is exposed for access outside the cluster is by using a service with a NodePort. The rest endpoint is accessible via port 31001. If you're on a different machine and run:

curl -X GET http://machine-running-k8s:31001

You'll get a successful response.

If running local:

curl -X GET http://localhost:31001 (or the same command as above)

You don't need a port forward to do that

**Comment by marcodlk** [comment] 2022-01-13 18:01
I *should not* need to port forward but for some reason I am unable to reach the service via localhost. I get the following error after it hangs for about a minute.
```
$ curl -X GET http://localhost:31001
curl: (52) Empty reply from server
```
The port forwarding exercise just shows that the issue seems to be the connection to the service.

**Comment by dreedyman** [comment] 2022-01-13 18:05
I've sent you 2 meeting requests, please login to https://meet.google.com/rja-qnui-gkm
